# Generated by Django 3.2.9 on 2022-11-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_articles_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='full_text_1',
            field=models.TextField(null=True, verbose_name='статья'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='full_text_2',
            field=models.TextField(null=True, verbose_name='статья'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='full_text_3',
            field=models.TextField(null=True, verbose_name='статья'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='full_text_4',
            field=models.TextField(null=True, verbose_name='статья'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='full_text_5',
            field=models.TextField(null=True, verbose_name='статья'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='full_text_6',
            field=models.TextField(null=True, verbose_name='статья'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
