# Generated by Django 3.2.9 on 2022-11-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20221114_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='full_text_1',
            field=models.TextField(null=True, verbose_name='статья-1'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='full_text_2',
            field=models.TextField(null=True, verbose_name='статья-2'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='full_text_3',
            field=models.TextField(null=True, verbose_name='статья-3'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='full_text_4',
            field=models.TextField(null=True, verbose_name='статья-4'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='full_text_5',
            field=models.TextField(null=True, verbose_name='статья-5'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='full_text_6',
            field=models.TextField(null=True, verbose_name='статья-6'),
        ),
    ]
